/** @jsxImportSource @emotion/react */
import Head from "next/head";
import { css } from "@emotion/react";

export default function Home() {
  const mainDivMainPage = css`
      width:100%;
      height:100%;
      text-align:center;
    `;
  return (
    <>
      <Head>
        <title>Create Ultimate App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main css={mainDivMainPage}>
        <div>
          ULTIMATE APP
        </div>
      </main>
    </>
  );
}
