/** @jsxImportSource @emotion/react */
import { css } from "@emotion/react";
import Head from "next/head";
import { useSelector } from "react-redux";


export default function Home() {
  const mainDivMainPage = css`
      width:100%;
      height:100%;
      text-align:center;
    `;
  const auth = useSelector((state)=>state.auth)
  console.log("auth",auth)
  return (
    <>
      <Head>
        <title>Create Ultimate App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main css={mainDivMainPage}>
        <div>
          {(!auth || !auth.logged) && "ULTIMATE APP" }
          {auth && auth.logged && auth.email}
        </div>
      </main>
    </>
  );
}
