/** @jsxImportSource @emotion/react */
import Head from "next/head";
import { css } from "@emotion/react";
import LayoutAuth from "@/containers/LayoutAuth/LayoutAuth";
import {InputEmail,InputPassword,Button} from "@/components";
import FormControl from "@/containers/FormControl/FormControl";

export default function Home() {
  const mainDivMainPage = css`
      width:100%;
      height:100%;
      text-align:center;
    `;

  const handleSubmit=(event)=>{
    if(event){
      event.preventDefault()
    }
    console.log("login page on submit")
  }
  return (
    <>
      <Head>
        <title>ورود</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main css={mainDivMainPage}>
        <LayoutAuth>
          <form onSubmit={handleSubmit}>
            <FormControl>
            <InputEmail type="email" placeholder="ایمیل"/>
            </FormControl>
            <FormControl>
            <InputPassword type="password" placeholder="رمز عبور"/>
            </FormControl>
            <FormControl>
            <Button type="submit">ارسال</Button>
            </FormControl>
          </form>
        </LayoutAuth>
      </main>
    </>
  );
}
