/** @jsxImportSource @emotion/react */
import Head from "next/head";
import { css } from "@emotion/react";
import LayoutAuth from "@/containers/LayoutAuth/LayoutAuth";
import {InputEmail,InputPassword,InputText,Button,H2,Space} from "@/components";
import FormControl from "@/containers/FormControl/FormControl";
import { useState } from "react";

export default function ChangePassword() {
  const mainDivMainPage = css`
      width:100%;
      height:100%;
      text-align:center;
    `;

  const [formValue,setFormValue] = useState({})

  const handleSubmit=(event)=>{
    if(event){
      event.preventDefault()
    }
    console.log("login page on submit",formValue)
  }

  const handleOnChange = (name,value) =>{
    setFormValue({
      ...formValue,
      [name]:value,
    })
  }


  return (
    <>
      <Head>
        <title>ثبت نام</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main css={mainDivMainPage}>
        <LayoutAuth>
          <Space/>
          <H2 align={"center"}>لطفا رمز عبور خود را تغییر دهید</H2>
          <form onSubmit={handleSubmit}>
            <FormControl>
              <InputPassword  onChange={(value)=> handleOnChange('password',value)} type="password" placeholder="رمز عبور"/>
            </FormControl>
            <FormControl>
              <InputPassword  onChange={(value)=> handleOnChange('password2',value)} type="password" placeholder="تکرار رمز عبور"/>
            </FormControl>
            <FormControl>
              <Button type="submit">بازنشانی</Button>
            </FormControl>
          </form>
        </LayoutAuth>
      </main>
    </>
  );
}
