/** @jsxImportSource @emotion/react */
import Head from "next/head";
import { css } from "@emotion/react";
import LayoutAuth from "@/containers/LayoutAuth/LayoutAuth";
import {InputEmail,InputPassword,InputText,Button,H2,Space,HyperLink} from "@/components";
import FormControl from "@/containers/FormControl/FormControl";
import { useState } from "react";
import { useDispatch,useSelector } from "react-redux";
import { REGISTER_ACTION } from "@/actions";

export default function Register() {
  const mainDivMainPage = css`
      width:100%;
      height:100%;
      text-align:center;
    `;

  const situtationControl = css`
    width:100%;
    display:flex;
    align-item:center;
    justify-content:space-evenly;
    flex-direction:row;
    height:fit-content;
    padding:.2rem;
  `;

  const [formValue,setFormValue] = useState({})
  const dispatch = useDispatch()
  const auth = useSelector((state)=>(state.auth))
  const handleSubmit=(event)=>{
    if(event){
      event.preventDefault()
    }
    dispatch(REGISTER_ACTION())
  }

  const handleOnChange = (name,value) =>{
    setFormValue({
      ...formValue,
      [name]:value,
    })
  }


  return (
    <>
      <Head>
        <title>ثبت نام</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main css={mainDivMainPage}>
        <LayoutAuth>
          <Space/>
          <H2 align={"center"}>لطفا برای ثبتا نام اطلاعات خود را وارد کنید</H2>
          <form onSubmit={handleSubmit}>
            <FormControl>
              <InputText onChange={(value)=> handleOnChange('name',value)} type="text" placeholder="نام"/>
            </FormControl>
            <FormControl>
              <InputEmail onChange={(value)=> handleOnChange('email',value)} type="email" placeholder="ایمیل"/>
            </FormControl>
            <FormControl>
              <InputPassword  onChange={(value)=> handleOnChange('password',value)} type="password" placeholder="رمز عبور"/>
            </FormControl>
            <FormControl>
              <InputPassword  onChange={(value)=> handleOnChange('password2',value)} type="password" placeholder="تکرار رمز عبور"/>
            </FormControl>
            <FormControl>
              <Button type="submit" loading={auth.loading}>ثبت نام</Button>
            </FormControl>
            <div css={situtationControl}>
              <HyperLink href="/login">
                وارد شوید
              </HyperLink>
              <HyperLink href="/forgot">
                فراموشی رمز عبور
              </HyperLink>
            </div>
          </form>
        </LayoutAuth>
      </main>
    </>
  );
}
