const actionTypse = {
  //LOGIN TYPES
  LOGIN_STARTED:"LOGIN_STARTED",
  LOGIN_SUCCESS:"LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  //REGISTERING TYPES
  REGISTER_STARTED:"REGISTER_STARTED",
  REGISTER_SUCCESS:"REGISTER_SUCCESS",
  REGISTER_FAILED: "REGISTER_FAILED",
  // JOB LIST TYPES
  GET_LIST_JOB_STARTED:"GET_LIST_JOB_STARTED",
  GET_LIST_JOB_SUCCESS:"GET_LIST_JOB_SUCCESS",
  GET_LIST_JOB_FAILED: "GET_LIST_JOB_FAILED",

}

export default actionTypse
